import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck, Check, ClipboardCheck, Download, FileBarChart, MapPin, Plus, Search, UsersRound } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { ResponsiveDialog } from '@/components/ui/responsive-dialog';
import { supabase } from '@/lib/supabase';
import { toast } from '@/hooks/use-toast';
import type { JgcAluno, JgcTurma } from '@/types/jovem-guarda';

type Can = (module: string, action: string) => boolean;
type Props = { section: string; alunos: JgcAluno[]; turmas: JgcTurma[]; can: Can; reload: () => void };
type Responsavel = { id:string; aluno_id:string; nome:string; vinculo:string; telefone:string; whatsapp:string|null; email:string|null; endereco:string|null; principal:boolean; autorizado_buscar:boolean; aluno?:{nome_completo:string}|null };
type Atividade = { id:string; titulo:string; tipo:string; descricao:string|null; data:string; hora_inicio:string|null; hora_fim:string|null; local:string|null; turma_id:string|null; status:string; turma?:{nome:string}|null };
type Diario = { id:string; turma_id:string; data:string; conteudo:string|null; observacoes:string|null; turma?:{nome:string}|null };
type FrequencyStatus = 'presente'|'ausente'|'justificada'|'atraso';

const today = new Date().toISOString().slice(0,10);
const dateLabel = (value:string) => new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`));

export function JgcOperationalSection({ section, alunos, turmas, can, reload }:Props) {
  if (section==='responsaveis') return <Responsaveis alunos={alunos} can={can}/>;
  if (section==='diario') return <DiarioTurma alunos={alunos} turmas={turmas} can={can}/>;
  if (section==='atividades') return <Atividades turmas={turmas} can={can}/>;
  if (section==='relatorios') return <Relatorios alunos={alunos} turmas={turmas} can={can}/>;
  return null;
}

function Head({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}) {
  return <div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action}</div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function Choice({value,onChange,options,placeholder='Selecione'}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];placeholder?:string}) {
  return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{options.map(item=><SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select>;
}
function Blank({icon:Icon,title,text}:{icon:typeof UsersRound;title:string;text:string}) {
  return <div className="rounded-3xl border border-dashed bg-white/70 px-6 py-12 text-center"><Icon className="mx-auto h-8 w-8 text-teal-700"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div>;
}

function Responsaveis({alunos,can}:{alunos:JgcAluno[];can:Can}) {
  const [items,setItems]=useState<Responsavel[]>([]); const [open,setOpen]=useState(false); const [search,setSearch]=useState('');
  const [form,setForm]=useState({aluno_id:'',nome:'',vinculo:'',telefone:'',whatsapp:'',email:'',endereco:'',principal:false,autorizado_buscar:false});
  const load=async()=>{const {data}=await supabase.from('jgc_responsaveis').select('*, aluno:jgc_alunos(nome_completo)').order('nome');setItems((data as unknown as Responsavel[])||[])};
  useEffect(()=>{void load()},[]);
  async function save(){if(!form.aluno_id||!form.nome.trim()||!form.vinculo.trim()||!form.telefone.trim())return toast({title:'Preencha aluno, nome, vínculo e telefone',variant:'destructive'});const {error}=await supabase.from('jgc_responsaveis').insert({...form,email:form.email||null,endereco:form.endereco||null,whatsapp:form.whatsapp||null});if(error)return toast({title:'Erro ao cadastrar responsável',description:error.message,variant:'destructive'});toast({title:'Responsável vinculado'});setOpen(false);void load()}
  const filtered=items.filter(item=>`${item.nome} ${item.aluno?.nome_completo||''} ${item.telefone}`.toLowerCase().includes(search.toLowerCase()));
  return <section><Head title="Responsáveis" subtitle="Contatos familiares reutilizados diretamente na ficha do aluno" action={can('responsaveis','criar')?<Button onClick={()=>setOpen(true)} className="bg-teal-700"><Plus className="mr-2 h-4 w-4"/>Novo responsável</Button>:undefined}/><div className="relative mb-4 max-w-xl"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="bg-white pl-10" placeholder="Responsável, aluno ou telefone..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.length?<div className="grid gap-3 md:grid-cols-2">{filtered.map(item=><Card key={item.id} className="rounded-2xl border-0 shadow-sm"><CardContent className="p-4"><div className="flex justify-between gap-3"><div><strong>{item.nome}</strong><p className="text-sm text-slate-500">{item.vinculo} de {item.aluno?.nome_completo}</p></div>{item.principal&&<Badge className="bg-teal-100 text-teal-800">Principal</Badge>}</div><div className="mt-3 text-sm text-slate-600"><p>{item.telefone}{item.whatsapp?' · WhatsApp '+item.whatsapp:''}</p>{item.autorizado_buscar&&<p className="mt-1 text-emerald-700"><Check className="mr-1 inline h-4 w-4"/>Autorizado a buscar</p>}</div></CardContent></Card>)}</div>:<Blank icon={UsersRound} title="Nenhum responsável" text="Vincule responsáveis aos alunos sem duplicar cadastros."/>}<ResponsiveDialog open={open} onOpenChange={setOpen} title="Novo responsável" description="O contato ficará disponível na ficha do aluno." onCancel={()=>setOpen(false)} onConfirm={save} confirmLabel="Vincular"><div className="grid gap-4 py-2 sm:grid-cols-2"><Field label="Aluno *"><Choice value={form.aluno_id} onChange={v=>setForm({...form,aluno_id:v})} options={alunos.map(a=>({value:a.id,label:a.nome_completo}))}/></Field><Field label="Nome *"><Input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></Field><Field label="Parentesco ou vínculo *"><Input value={form.vinculo} onChange={e=>setForm({...form,vinculo:e.target.value})}/></Field><Field label="Telefone *"><Input value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/></Field><Field label="WhatsApp"><Input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></Field><Field label="E-mail"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Endereço"><Textarea value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/></Field><div className="space-y-2 pt-6"><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.principal} onChange={e=>setForm({...form,principal:e.target.checked})}/>Responsável principal</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.autorizado_buscar} onChange={e=>setForm({...form,autorizado_buscar:e.target.checked})}/>Autorizado a buscar</label></div></div></ResponsiveDialog></section>
}

function DiarioTurma({alunos,turmas,can}:{alunos:JgcAluno[];turmas:JgcTurma[];can:Can}) {
  const [items,setItems]=useState<Diario[]>([]); const [open,setOpen]=useState(false);
  const [turmaId,setTurmaId]=useState(''); const [data,setData]=useState(today); const [conteudo,setConteudo]=useState(''); const [observacoes,setObservacoes]=useState('');
  const [frequency,setFrequency]=useState<Record<string,FrequencyStatus>>({});
  const classStudents=alunos.filter(a=>a.turma_id===turmaId&&a.situacao==='ativo');
  const load=async()=>{const {data}=await supabase.from('jgc_diarios').select('*, turma:jgc_turmas(nome)').order('data',{ascending:false}).limit(30);setItems((data as unknown as Diario[])||[])};
  useEffect(()=>{void load()},[]);
  useEffect(()=>{setFrequency(Object.fromEntries(classStudents.map(a=>[a.id,'presente'])))},[turmaId,alunos.length]);
  async function save(){if(!turmaId||!data)return toast({title:'Selecione turma e data',variant:'destructive'});const {data:diario,error}=await supabase.from('jgc_diarios').upsert({turma_id:turmaId,data,conteudo,observacoes},{onConflict:'turma_id,data'}).select('id').single();if(error||!diario)return toast({title:'Erro ao salvar diário',description:error?.message,variant:'destructive'});const rows=classStudents.map(a=>({diario_id:diario.id,aluno_id:a.id,status:frequency[a.id]||'presente'}));if(rows.length){const {error:freqError}=await supabase.from('jgc_frequencias').upsert(rows,{onConflict:'diario_id,aluno_id'});if(freqError)return toast({title:'Erro ao salvar frequência',description:freqError.message,variant:'destructive'})}toast({title:'Diário e chamada registrados'});setOpen(false);void load()}
  return <section><Head title="Diário de Turma" subtitle="Registre conteúdo, observações e chamada no mesmo encontro" action={can('frequencia','registrar')?<Button onClick={()=>setOpen(true)} className="bg-amber-400 text-slate-950 hover:bg-amber-300"><ClipboardCheck className="mr-2 h-4 w-4"/>Fazer chamada</Button>:undefined}/>{items.length?<div className="space-y-3">{items.map(item=><Card key={item.id} className="rounded-2xl border-0 shadow-sm"><CardContent className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 font-bold text-amber-800">{new Date(`${item.data}T12:00:00`).getDate()}</div><div><strong>{item.turma?.nome}</strong><p className="text-sm text-slate-500">{item.conteudo||'Conteúdo não informado'}</p><p className="text-xs text-slate-400">{dateLabel(item.data)}</p></div></CardContent></Card>)}</div>:<Blank icon={ClipboardCheck} title="Nenhum diário registrado" text="Selecione uma turma e faça a primeira chamada."/>}<ResponsiveDialog open={open} onOpenChange={setOpen} title="Diário e chamada" description="A frequência alimentará automaticamente os indicadores." onCancel={()=>setOpen(false)} onConfirm={save} confirmLabel="Salvar encontro"><div className="max-h-[68vh] space-y-4 overflow-y-auto pr-2"><div className="grid gap-4 sm:grid-cols-2"><Field label="Turma *"><Choice value={turmaId} onChange={setTurmaId} options={turmas.filter(t=>t.status==='ativa').map(t=>({value:t.id,label:t.nome}))}/></Field><Field label="Data *"><Input type="date" value={data} onChange={e=>setData(e.target.value)}/></Field></div><Field label="Conteúdo ou atividade"><Textarea value={conteudo} onChange={e=>setConteudo(e.target.value)}/></Field><Field label="Observações gerais"><Textarea value={observacoes} onChange={e=>setObservacoes(e.target.value)}/></Field>{turmaId&&<div><Label>Chamada · {classStudents.length} aluno(s)</Label><div className="mt-2 space-y-2">{classStudents.map(a=><div key={a.id} className="grid items-center gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_190px]"><span className="text-sm font-medium">{a.nome_completo}</span><Choice value={frequency[a.id]||'presente'} onChange={v=>setFrequency({...frequency,[a.id]:v as FrequencyStatus})} options={[{value:'presente',label:'Presente'},{value:'ausente',label:'Ausente'},{value:'justificada',label:'Ausência justificada'},{value:'atraso',label:'Atraso'}]}/></div>)}</div></div>}</div></ResponsiveDialog></section>
}

function Atividades({turmas,can}:{turmas:JgcTurma[];can:Can}) {
  const [items,setItems]=useState<Atividade[]>([]);const [open,setOpen]=useState(false);
  const [form,setForm]=useState({titulo:'',tipo:'pedagogica',descricao:'',data:today,hora_inicio:'',hora_fim:'',local:'',turma_id:''});
  const load=async()=>{const {data}=await supabase.from('jgc_atividades').select('*, turma:jgc_turmas(nome)').order('data',{ascending:false});setItems((data as unknown as Atividade[])||[])};
  useEffect(()=>{void load()},[]);
  async function save(){if(!form.titulo.trim()||!form.data)return toast({title:'Informe título e data',variant:'destructive'});const payload={...form,hora_inicio:form.hora_inicio||null,hora_fim:form.hora_fim||null,local:form.local||null,turma_id:form.turma_id||null};const {error}=await supabase.from('jgc_atividades').insert(payload);if(error)return toast({title:'Erro ao criar atividade',description:error.message,variant:'destructive'});toast({title:'Atividade criada'});setOpen(false);void load()}
  async function cancel(item:Atividade){const {error}=await supabase.from('jgc_atividades').update({status:'cancelada'}).eq('id',item.id);if(error)return toast({title:'Erro ao cancelar',description:error.message,variant:'destructive'});void load()}
  return <section><Head title="Atividades" subtitle="Aulas, oficinas, eventos, visitas e ações coletivas" action={can('atividades','criar')?<Button onClick={()=>setOpen(true)} className="bg-teal-700"><Plus className="mr-2 h-4 w-4"/>Nova atividade</Button>:undefined}/>{items.length?<div className="grid gap-4 md:grid-cols-2">{items.map(item=><Card key={item.id} className="rounded-2xl border-0 shadow-sm"><CardHeader><div className="flex justify-between"><Badge variant="outline">{item.tipo}</Badge><Badge className={item.status==='cancelada'?'bg-rose-100 text-rose-800':'bg-emerald-100 text-emerald-800'}>{item.status}</Badge></div><CardTitle>{item.titulo}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-600"><p>{item.descricao}</p><p><CalendarCheck className="mr-2 inline h-4 w-4"/>{dateLabel(item.data)} {item.hora_inicio?.slice(0,5)}</p>{item.local&&<p><MapPin className="mr-2 inline h-4 w-4"/>{item.local}</p>}<p>{item.turma?.nome||'Atividade geral'}</p>{can('atividades','excluir')&&item.status==='ativa'&&<Button variant="outline" size="sm" onClick={()=>void cancel(item)}>Cancelar atividade</Button>}</CardContent></Card>)}</div>:<Blank icon={CalendarCheck} title="Nenhuma atividade" text="Cadastre a programação socioeducativa do projeto."/>}<ResponsiveDialog open={open} onOpenChange={setOpen} title="Nova atividade" description="A atividade será associada à turma e ao histórico dos participantes." onCancel={()=>setOpen(false)} onConfirm={save} confirmLabel="Criar atividade"><div className="grid gap-4 py-2 sm:grid-cols-2"><Field label="Título *"><Input value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})}/></Field><Field label="Tipo"><Choice value={form.tipo} onChange={v=>setForm({...form,tipo:v})} options={['pedagogica','esportiva','cultural','educativa','palestra','oficina','evento','acao_coletiva','outra'].map(v=>({value:v,label:v.replaceAll('_',' ')}))}/></Field><Field label="Data *"><Input type="date" value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/></Field><Field label="Turma"><Choice value={form.turma_id} onChange={v=>setForm({...form,turma_id:v})} options={turmas.map(t=>({value:t.id,label:t.nome}))}/></Field><Field label="Início"><Input type="time" value={form.hora_inicio} onChange={e=>setForm({...form,hora_inicio:e.target.value})}/></Field><Field label="Fim"><Input type="time" value={form.hora_fim} onChange={e=>setForm({...form,hora_fim:e.target.value})}/></Field><Field label="Local"><Input value={form.local} onChange={e=>setForm({...form,local:e.target.value})}/></Field><Field label="Descrição"><Textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></Field></div></ResponsiveDialog></section>
}

function Relatorios({alunos,turmas,can}:{alunos:JgcAluno[];turmas:JgcTurma[];can:Can}) {
  const [frequency,setFrequency]=useState<{aluno_id:string;total:number;presencas:number;faltas:number;percentual:number}[]>([]);
  useEffect(()=>{void supabase.from('jgc_frequencia_resumo').select('*').then(({data})=>setFrequency(data||[]))},[]);
  const active=alunos.filter(a=>a.situacao==='ativo').length;const withoutClass=alunos.filter(a=>a.situacao==='ativo'&&!a.turma_id).length;
  const avg=frequency.length?frequency.reduce((sum,item)=>sum+Number(item.percentual||0),0)/frequency.length:0;
  function exportCsv(){if(!can('relatorios','exportar'))return;const rows=[['Matrícula','Aluno','Situação','Turma','Escola','Frequência'],...alunos.map(a=>[a.matricula,a.nome_completo,a.situacao,a.turma?.nome||'',a.escola_nome||'',frequency.find(f=>f.aluno_id===a.id)?.percentual?.toString()||''])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`jovem-guarda-${today}.csv`;link.click();URL.revokeObjectURL(url)}
  return <section><Head title="Relatórios" subtitle="Visão administrativa e pedagógica limitada aos dados autorizados" action={can('relatorios','exportar')?<Button onClick={exportCsv} className="bg-teal-700"><Download className="mr-2 h-4 w-4"/>Exportar CSV</Button>:undefined}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ReportCard label="Alunos ativos" value={active}/><ReportCard label="Turmas ativas" value={turmas.filter(t=>t.status==='ativa').length}/><ReportCard label="Sem turma" value={withoutClass}/><ReportCard label="Frequência média" value={`${avg.toFixed(1)}%`}/></div><Card className="mt-5 rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><FileBarChart className="h-5 w-5 text-teal-700"/>Frequência individual</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-3">Aluno</th><th className="p-3">Turma</th><th className="p-3">Presenças</th><th className="p-3">Faltas</th><th className="p-3">Percentual</th></tr></thead><tbody>{alunos.map(a=>{const f=frequency.find(item=>item.aluno_id===a.id);return <tr key={a.id} className="border-b last:border-0"><td className="p-3 font-medium">{a.nome_completo}</td><td className="p-3">{a.turma?.nome||'—'}</td><td className="p-3">{f?.presencas||0}</td><td className="p-3">{f?.faltas||0}</td><td className="p-3"><Badge className={Number(f?.percentual||0)<75?'bg-rose-100 text-rose-800':'bg-emerald-100 text-emerald-800'}>{Number(f?.percentual||0).toFixed(1)}%</Badge></td></tr>})}</tbody></table></CardContent></Card></section>
}
function ReportCard({label,value}:{label:string;value:number|string}){return <Card className="rounded-2xl border-0 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></CardContent></Card>}
