import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, CalendarCheck, CheckCircle2, Clock3, FileText, HeartPulse, ListChecks, Plus, UsersRound } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { ResponsiveDialog } from '@/components/ui/responsive-dialog';
import { supabase } from '@/lib/supabase';
import { toast } from '@/hooks/use-toast';
import type { JgcAluno, JgcAtendimento, JgcPerfil } from '@/types/jovem-guarda';

type Can=(module:string,action:string)=>boolean;
type Row={id:string;[key:string]:unknown};
const today=new Date().toISOString().slice(0,10);
const dateLabel=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T12:00:00Z`)):'—';

export function JgcStudentJourney({student,services,profile,onBack,onService,can}:{student:JgcAluno;services:JgcAtendimento[];profile:JgcPerfil;onBack:()=>void;onService:()=>void;can:Can}) {
  const [responsaveis,setResponsaveis]=useState<Row[]>([]);const [frequency,setFrequency]=useState<Row|null>(null);const [activities,setActivities]=useState<Row[]>([]);
  const [actions,setActions]=useState<Row[]>([]);const [referrals,setReferrals]=useState<Row[]>([]);const [history,setHistory]=useState<Row[]>([]);
  const [actionOpen,setActionOpen]=useState(false);const [referralOpen,setReferralOpen]=useState(false);
  const [action,setAction]=useState({descricao:'',prazo:today,status:'pendente'});const [referral,setReferral]=useState({destino:'',motivo:'',data:today,observacoes:'',status:'pendente'});
  const sensitive=profile==='gestor'||profile==='multiprofissional';
  async function load(){const [r,f,a,ac,en,h]=await Promise.all([
    supabase.from('jgc_responsaveis').select('*').eq('aluno_id',student.id).order('principal',{ascending:false}),
    supabase.from('jgc_frequencia_resumo').select('*').eq('aluno_id',student.id).maybeSingle(),
    supabase.from('jgc_atividade_participantes').select('atividade:jgc_atividades(*)').eq('aluno_id',student.id),
    supabase.from('jgc_acoes').select('*').eq('aluno_id',student.id).order('prazo'),
    supabase.from('jgc_encaminhamentos').select('*').eq('aluno_id',student.id).order('data',{ascending:false}),
    supabase.rpc('jgc_historico_aluno',{_aluno_id:student.id}),
  ]);setResponsaveis((r.data as Row[])||[]);setFrequency(f.data as Row|null);setActivities(((a.data||[]) as {atividade:Row}[]).map(x=>x.atividade).filter(Boolean));setActions((ac.data as Row[])||[]);setReferrals((en.data as Row[])||[]);setHistory((h.data as Row[])||[])}
  useEffect(()=>{void load()},[student.id]);
  async function saveAction(){if(!action.descricao.trim())return toast({title:'Descreva a ação',variant:'destructive'});const {error}=await supabase.from('jgc_acoes').insert({...action,aluno_id:student.id});if(error)return toast({title:'Erro ao criar ação',description:error.message,variant:'destructive'});setActionOpen(false);toast({title:'Ação adicionada ao plano'});void load()}
  async function saveReferral(){if(!referral.destino.trim()||!referral.motivo.trim())return toast({title:'Informe destino e motivo',variant:'destructive'});const {error}=await supabase.from('jgc_encaminhamentos').insert({...referral,aluno_id:student.id});if(error)return toast({title:'Erro ao encaminhar',description:error.message,variant:'destructive'});setReferralOpen(false);toast({title:'Encaminhamento registrado'});void load()}
  async function finishAction(id:string){const {error}=await supabase.from('jgc_acoes').update({status:'concluida'}).eq('id',id);if(error)return toast({title:'Erro ao concluir',description:error.message,variant:'destructive'});void load()}
  return <section><button onClick={onBack} className="mb-4 flex items-center gap-2 text-sm font-medium text-teal-800"><ArrowLeft className="h-4 w-4"/>Voltar aos alunos</button><div className="mb-5 flex flex-col gap-4 rounded-3xl bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-teal-700 text-lg font-bold text-white">{student.nome_completo.split(' ').slice(0,2).map(v=>v[0]).join('')}</div><div className="flex-1"><div className="flex flex-wrap gap-2"><h2 className="text-2xl font-bold">{student.nome_completo}</h2><Badge className="bg-emerald-100 text-emerald-800">{student.situacao}</Badge></div><p className="text-sm text-slate-500">{student.matricula} · Entrada {dateLabel(student.data_entrada)}</p></div>{sensitive&&can('acompanhamento','criar')&&<Button onClick={onService} className="bg-teal-700"><Plus className="mr-2 h-4 w-4"/>Atendimento</Button>}</div>
  <Tabs defaultValue="geral"><TabsList className="mb-4 h-auto w-full justify-start overflow-x-auto bg-white p-1"><TabsTrigger value="geral">Visão geral</TabsTrigger><TabsTrigger value="frequencia">Frequência</TabsTrigger><TabsTrigger value="atividades">Atividades</TabsTrigger>{sensitive&&<TabsTrigger value="acompanhamento">Acompanhamento</TabsTrigger>}<TabsTrigger value="familia">Família</TabsTrigger>{sensitive&&<TabsTrigger value="saude">Saúde</TabsTrigger>}<TabsTrigger value="documentos">Documentos</TabsTrigger><TabsTrigger value="historico">Histórico</TabsTrigger></TabsList>
  <TabsContent value="geral"><div className="grid gap-4 md:grid-cols-2"><Info title="Escola e projeto" rows={[['Escola',student.escola_nome],['Série/Ano',student.serie_ano],['Turma',student.turma?.nome],['Horário',`${student.projeto_hora_inicio?.slice(0,5)||'—'} às ${student.projeto_hora_fim?.slice(0,5)||'—'}`]]}/><Info title="Dados pessoais" rows={[['Nascimento',dateLabel(student.data_nascimento)],['Naturalidade',[student.naturalidade_cidade,student.naturalidade_uf].filter(Boolean).join(' - ')],['CPF',student.cpf?`•••.•••.•••-${student.cpf.slice(-2)}`:'Não informado'],['NIS',student.nis?'Informado':'Não informado']]}/></div></TabsContent>
  <TabsContent value="frequencia"><div className="grid gap-4 sm:grid-cols-4"><Metric label="Encontros" value={String(frequency?.total||0)}/><Metric label="Presenças" value={String(frequency?.presencas||0)}/><Metric label="Faltas" value={String(frequency?.faltas||0)}/><Metric label="Frequência" value={`${Number(frequency?.percentual||0).toFixed(1)}%`}/></div></TabsContent>
  <TabsContent value="atividades">{activities.length?<div className="grid gap-3 md:grid-cols-2">{activities.map(item=><Card key={String(item.id)}><CardContent className="p-4"><strong>{String(item.titulo)}</strong><p className="mt-1 text-sm text-slate-500">{String(item.tipo)} · {dateLabel(String(item.data))}</p></CardContent></Card>)}</div>:<Blank icon={CalendarCheck} title="Sem atividades individuais" text="Atividades da turma também aparecem no histórico consolidado."/ >}</TabsContent>
  {sensitive&&<TabsContent value="acompanhamento"><div className="mb-4 flex flex-wrap gap-2">{can('acompanhamento','criar')&&<><Button size="sm" onClick={()=>setActionOpen(true)}><ListChecks className="mr-2 h-4 w-4"/>Nova ação</Button><Button size="sm" variant="outline" onClick={()=>setReferralOpen(true)}>Novo encaminhamento</Button></>}</div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Plano de acompanhamento</CardTitle></CardHeader><CardContent className="space-y-2">{actions.length?actions.map(item=><div key={String(item.id)} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><strong className="text-sm">{String(item.descricao)}</strong><Badge variant="outline">{String(item.status)}</Badge></div><p className="mt-1 text-xs text-slate-500">Prazo: {dateLabel(String(item.prazo||''))}</p>{can('acompanhamento','editar')&&item.status!=='concluida'&&<Button className="mt-2" size="sm" variant="outline" onClick={()=>void finishAction(String(item.id))}><CheckCircle2 className="mr-1 h-3 w-3"/>Concluir</Button>}</div>):<p className="text-sm text-slate-500">Sem ações pendentes.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Encaminhamentos</CardTitle></CardHeader><CardContent className="space-y-2">{referrals.length?referrals.map(item=><div key={String(item.id)} className="rounded-xl border p-3"><div className="flex justify-between"><strong>{String(item.destino)}</strong><Badge variant="outline">{String(item.status)}</Badge></div><p className="text-sm text-slate-500">{String(item.motivo)}</p></div>):<p className="text-sm text-slate-500">Sem encaminhamentos.</p>}</CardContent></Card></div><div className="mt-4 space-y-2">{services.map(s=><Card key={s.id}><CardContent className="p-4"><div className="flex justify-between"><strong>{s.motivo}</strong><Badge variant="outline">{s.privacidade}</Badge></div><p className="mt-1 text-sm text-slate-600">{s.relato}</p></CardContent></Card>)}</div></TabsContent>}
  <TabsContent value="familia">{responsaveis.length?<div className="grid gap-3 md:grid-cols-2">{responsaveis.map(item=><Card key={String(item.id)}><CardContent className="p-4"><div className="flex justify-between"><strong>{String(item.nome)}</strong>{Boolean(item.principal)&&<Badge>Principal</Badge>}</div><p className="text-sm text-slate-500">{String(item.vinculo)} · {String(item.telefone)}</p></CardContent></Card>)}</div>:<Blank icon={UsersRound} title="Sem responsáveis vinculados" text="Cadastre o núcleo familiar no módulo Responsáveis."/ >}</TabsContent>
  {sensitive&&<TabsContent value="saude"><Info title="Informações essenciais à segurança" rows={[['Tipo sanguíneo',student.saude?.tipo_sanguineo],['Condição',student.saude?.possui_condicao==='sim'?student.saude.condicao_saude:'Não informada'],['Medicamentos',student.saude?.usa_medicamento==='sim'?student.saude.medicamentos:'Não informado'],['Orientação',student.saude?.orientacao_medicamento]]}/></TabsContent>}
  <TabsContent value="documentos"><Blank icon={FileText} title="Documentos integrados" text="Use o acervo documental existente do setor; não há armazenamento duplicado."/><Button asChild className="mt-4" variant="outline"><Link to="/admin/documentos/jovem-guarda">Abrir documentos do Jovem Guarda</Link></Button></TabsContent>
  <TabsContent value="historico">{history.length?<div className="relative ml-3 border-l-2 border-teal-100 pl-6">{history.map((item,index)=><div key={`${String(item.referencia_id)}-${index}`} className="relative pb-6"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full bg-teal-600 ring-4 ring-teal-50"/><div className="flex flex-wrap gap-2"><strong>{String(item.titulo)}</strong><Badge variant="outline">{String(item.tipo)}</Badge></div><p className="text-sm text-slate-500">{String(item.descricao||'')}</p><p className="text-xs text-slate-400">{dateLabel(String(item.data_hora))}</p></div>)}</div>:<Blank icon={Clock3} title="Histórico inicial" text="Os eventos autorizados serão consolidados automaticamente."/ >}</TabsContent></Tabs>
  <ResponsiveDialog open={actionOpen} onOpenChange={setActionOpen} title="Nova ação futura" description="A ação aparecerá nas pendências e no plano do aluno." onCancel={()=>setActionOpen(false)} onConfirm={saveAction} confirmLabel="Criar ação"><div className="space-y-4 py-2"><Field label="Descrição *"><Textarea value={action.descricao} onChange={e=>setAction({...action,descricao:e.target.value})}/></Field><Field label="Prazo"><Input type="date" value={action.prazo} onChange={e=>setAction({...action,prazo:e.target.value})}/></Field></div></ResponsiveDialog>
  <ResponsiveDialog open={referralOpen} onOpenChange={setReferralOpen} title="Novo encaminhamento" description="Registre o envio, sem administrar o trabalho do órgão externo." onCancel={()=>setReferralOpen(false)} onConfirm={saveReferral} confirmLabel="Registrar"><div className="space-y-4 py-2"><Field label="Destino *"><Select value={referral.destino} onValueChange={v=>setReferral({...referral,destino:v})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{['CRAS','CREAS','Conselho Tutelar','Unidade de Saúde','Serviço especializado','Outro'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Field label="Motivo *"><Textarea value={referral.motivo} onChange={e=>setReferral({...referral,motivo:e.target.value})}/></Field><Field label="Data"><Input type="date" value={referral.data} onChange={e=>setReferral({...referral,data:e.target.value})}/></Field><Field label="Observações"><Textarea value={referral.observacoes} onChange={e=>setReferral({...referral,observacoes:e.target.value})}/></Field></div></ResponsiveDialog></section>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Info({title,rows}:{title:string;rows:[string,string|null|undefined][]}){return <Card className="rounded-2xl border-0 shadow-sm"><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="divide-y">{rows.map(([k,v])=><div key={k} className="flex justify-between gap-4 py-3 text-sm"><span className="text-slate-500">{k}</span><strong className="text-right">{v||'Não informado'}</strong></div>)}</CardContent></Card>}
function Metric({label,value}:{label:string;value:string}){return <Card><CardContent className="p-5"><p className="text-xs uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>}
function Blank({icon:Icon,title,text}:{icon:typeof Clock3;title:string;text:string}){return <div className="rounded-2xl border border-dashed p-8 text-center"><Icon className="mx-auto h-7 w-7 text-teal-700"/><h3 className="mt-2 font-semibold">{title}</h3><p className="text-sm text-slate-500">{text}</p></div>}
