-- Adiciona coluna prioridade_padrao em fala_assuntos
ALTER TABLE public.fala_assuntos
ADD COLUMN IF NOT EXISTS prioridade_padrao public.fala_prioridade NOT NULL DEFAULT 'media';

-- Define a prioridade padrao para cada assunto
UPDATE public.fala_assuntos a
SET prioridade_padrao = p.prioridade
FROM public.fala_secretarias s,
(VALUES
  ('DEMUTRAN', 'Buraco na pista', 'media'::public.fala_prioridade),
  ('DEMUTRAN', 'Semafaro quebrado ou com defeito', 'alta'),
  ('DEMUTRAN', 'Sinalizacao vertical danificada ou faltando', 'media'),
  ('DEMUTRAN', 'Sinalizacao horizontal apagada (faixas de pedestre, lombadas)', 'media'),
  ('DEMUTRAN', 'Placa de transito faltando ou ilegivel', 'media'),
  ('DEMUTRAN', 'Acidente de transito com danos', 'alta'),
  ('DEMUTRAN', 'Veiculo abandonado na via publica', 'baixa'),
  ('DEMUTRAN', 'Estacionamento irregular em vias', 'baixa'),
  ('DEMUTRAN', 'Calcada obstruida por veiculos', 'baixa'),
  ('DEMUTRAN', 'Faixa de pedestre apagada ou mal conservada', 'media'),
  ('DEMUTRAN', 'Lombada danificada ou necessaria', 'media'),
  ('DEMUTRAN', 'Cruzamento perigoso sem sinalizacao', 'alta'),
  ('DEMUTRAN', 'Excesso de velocidade em vias residenciais', 'alta'),
  ('DEMUTRAN', 'Area de escola sem sinalizacao adequada', 'urgente'),
  ('DEMUTRAN', 'Semafaro com temporizacao errada', 'media'),
  ('DEMUTRAN', 'Poste de iluminacao com defeito na via', 'baixa'),
  ('DEMUTRAN', 'Redutor de velocidade quebrado', 'media'),
  ('DEMUTRAN', 'Sinalizacao de obra inadequada', 'media'),
  ('DEMUTRAN', 'Ciclofaixa obstruida ou danificada', 'baixa'),
  ('DEMUTRAN', 'Solicitacao de vaga de estacionamento para idoso/PCD', 'media'),
  ('DEMUTRAN', 'Recurso de multa de transito', 'baixa'),
  ('DEMUTRAN', 'Veiculo apreendido no patio', 'baixa'),
  ('DEMUTRAN', 'Educacao no transito para escolas', 'baixa'),
  ('DEMUTRAN', 'Fiscalizacao de mototaxistas e taxistas', 'media'),
  ('DEMUTRAN', 'Outro', 'media'),
  ('GM', 'Viatura solicitada para patrulhamento', 'media'),
  ('GM', 'Solicitacao de ronda escolar (ROPE)', 'alta'),
  ('GM', 'Apoio em eventos publicos (shows, feiras, festas)', 'baixa'),
  ('GM', 'Vandalismo em patrimonio publico (pracas, predios)', 'media'),
  ('GM', 'Atendimento a ocorrencias em vias publicas', 'alta'),
  ('GM', 'Abordagem de pessoas suspeitas', 'alta'),
  ('GM', 'Cameras de monitoramento com defeito', 'media'),
  ('GM', 'Alarme comunitaria acionado', 'alta'),
  ('GM', 'Brigada voluntaria para apoio', 'baixa'),
  ('GM', 'Seguranca em pracas e parques', 'baixa'),
  ('GM', 'Patrulhamento noturno em bairros', 'media'),
  ('GM', 'Atendimento a idosos em situacao de risco', 'alta'),
  ('GM', 'Apoio a pessoas em situacao de rua', 'media'),
  ('GM', 'Falta de iluminacao em vias publicas', 'media'),
  ('GM', 'Solicitacao de viatura para ocorrencia', 'alta'),
  ('GM', 'Guarda em escolas municipais', 'alta'),
  ('GM', 'Acoes preventivas em comunidades', 'baixa'),
  ('GM', 'Conselho comunitario de seguranca', 'baixa'),
  ('GM', 'Ciclovias e seguranca para ciclistas', 'media'),
  ('GM', 'Denuncia de som alto e perturbacao', 'baixa'),
  ('GM', 'Apoio ao DEMUTRAN em blitz', 'media'),
  ('GM', 'Apoio a Defesa Civil em emergencias', 'urgente'),
  ('GM', 'Fiscalizacao de comercios irregulares', 'media'),
  ('GM', 'Acompanhamento de pessoas com transtornos', 'alta'),
  ('GM', 'Outro', 'media'),
  ('GC', 'Vigilancia em escolas municipais', 'alta'),
  ('GC', 'Seguranca em hospitais publicos', 'alta'),
  ('GC', 'Monitoramento em pracas e parques', 'baixa'),
  ('GC', 'Vigilancia em predios publicos', 'media'),
  ('GC', 'Apoio a eventos comunitarios', 'baixa'),
  ('GC', 'Fiscalizacao de portarias', 'baixa'),
  ('GC', 'Controle de acesso em orgaos publicos', 'baixa'),
  ('GC', 'Acoes de prevencao em feiras', 'baixa'),
  ('GC', 'Ronda em terminais de onibus', 'media'),
  ('GC', 'Seguranca em creches', 'alta'),
  ('GC', 'Vigilancia em postos de saude', 'media'),
  ('GC', 'Apoio a campanhas educativas', 'baixa'),
  ('GC', 'Patrulhamento em areas de lazer', 'baixa'),
  ('GC', 'Orientacao a funcionarios publicos', 'baixa'),
  ('GC', 'Fiscalizacao de obras publicas', 'media'),
  ('GC', 'Seguranca em ginasios esportivos', 'media'),
  ('GC', 'Apoio a idosos em reparticoes', 'baixa'),
  ('GC', 'Controle de entrada em escolas', 'media'),
  ('GC', 'Vigilancia em museus e centros culturais', 'baixa'),
  ('GC', 'Apoio a acoes da Guarda Municipal', 'media'),
  ('GC', 'Seguranca em cemiterios publicos', 'baixa'),
  ('GC', 'Fiscalizacao de estacionamentos publicos', 'baixa'),
  ('GC', 'Apoio a campanhas de vacinacao', 'baixa'),
  ('GC', 'Orientacao a visitantes', 'baixa'),
  ('GC', 'Outro', 'media'),
  ('JOVEM', 'Oficinas educativas para jovens', 'baixa'),
  ('JOVEM', 'Capacitacao profissional', 'baixa'),
  ('JOVEM', 'Primeiro emprego e estagio', 'baixa'),
  ('JOVEM', 'Escolinha de esporte (futebol, volei, basquete)', 'baixa'),
  ('JOVEM', 'Projetos culturais (musica, danca, teatro)', 'baixa'),
  ('JOVEM', 'Campeonatos esportivos entre escolas', 'baixa'),
  ('JOVEM', 'Apoio a jovens em vulnerabilidade', 'alta'),
  ('JOVEM', 'Prevencao a drogas e alcool', 'alta'),
  ('JOVEM', 'Reforco escolar e monitoria', 'baixa'),
  ('JOVEM', 'Biblioteca comunitaria e leitura', 'baixa'),
  ('JOVEM', 'Acoes de lazer e recriacao', 'baixa'),
  ('JOVEM', 'Festivais de musica jovem', 'baixa'),
  ('JOVEM', 'Danca e apresentacoes culturais', 'baixa'),
  ('JOVEM', 'Passeios educativos e visitas tecnicas', 'baixa'),
  ('JOVEM', 'Programa de aprendizagem', 'baixa'),
  ('JOVEM', 'Artes marciais e defesa pessoal', 'baixa'),
  ('JOVEM', 'Teatro comunitaria', 'baixa'),
  ('JOVEM', 'Esporte adaptado para PCD', 'baixa'),
  ('JOVEM', 'Feira de profissoes e carreiras', 'baixa'),
  ('JOVEM', 'Campanhas de doacao e voluntariado', 'baixa'),
  ('JOVEM', 'Educacao no transito para jovens', 'baixa'),
  ('JOVEM', 'Palestras sobre cidadania', 'baixa'),
  ('JOVEM', 'Oficinas de empreendedorismo', 'baixa'),
  ('JOVEM', 'Acompanhamento psicossocial', 'alta'),
  ('JOVEM', 'Outro', 'baixa'),
  ('ROPE', 'Patrulhamento na entrada das escolas', 'alta'),
  ('ROPE', 'Patrulhamento na saida das escolas', 'alta'),
  ('ROPE', 'Solicitacao de viatura na escola', 'alta'),
  ('ROPE', 'Presenca de estranhos no entorno escolar', 'urgente'),
  ('ROPE', 'Transito caotico proximo a escola', 'alta'),
  ('ROPE', 'Ponto de onibus escolar sem seguranca', 'alta'),
  ('ROPE', 'Vandalismo dentro da escola', 'media'),
  ('ROPE', 'Furto ou roubo nas imediacoes', 'urgente'),
  ('ROPE', 'Brigas entre alunos na saida', 'alta'),
  ('ROPE', 'Abordagem de veiculos suspeitos', 'alta'),
  ('ROPE', 'Sinalizacao de transito na escola', 'media'),
  ('ROPE', 'Faixa de pedestre apagada na escola', 'media'),
  ('ROPE', 'Iluminacao publica na via escolar', 'media'),
  ('ROPE', 'Ameaca a alunos ou professores', 'urgente'),
  ('ROPE', 'Consumo de drogas proximo a escola', 'urgente'),
  ('ROPE', 'Apoio em eventos escolares', 'baixa'),
  ('ROPE', 'Ronda noturna nas escolas', 'media'),
  ('ROPE', 'Presenca de animais soltos na escola', 'baixa'),
  ('ROPE', 'Aluno desaparecido no trajeto', 'urgente'),
  ('ROPE', 'Acoes educativas nas escolas', 'baixa'),
  ('ROPE', 'Orientacao sobre bullying', 'media'),
  ('ROPE', 'Ciclovia segura para alunos', 'media'),
  ('ROPE', 'Acompanhamento de alunos com deficiencia', 'media'),
  ('ROPE', 'Reuniao com diretores e pais', 'baixa'),
  ('ROPE', 'Outro', 'media'),
  ('DCIV', 'Area de risco de deslizamento', 'urgente'),
  ('DCIV', 'Area de risco de enchente', 'urgente'),
  ('DCIV', 'Alagamento em via publica', 'alta'),
  ('DCIV', 'Transbordamento de rio ou corrego', 'urgente'),
  ('DCIV', 'Deslizamento de terra em encosta', 'urgente'),
  ('DCIV', 'Desabamento de imovel', 'urgente'),
  ('DCIV', 'Queda de arvore em via', 'alta'),
  ('DCIV', 'Queda de poste', 'alta'),
  ('DCIV', 'Soterramento em areas urbanas', 'urgente'),
  ('DCIV', 'Seca prolongada', 'alta'),
  ('DCIV', 'Falta de agua em comunidades', 'alta'),
  ('DCIV', 'Ventania e vendaval', 'alta'),
  ('DCIV', 'Granizo e tempestade', 'alta'),
  ('DCIV', 'Incendio em area de mata', 'urgente'),
  ('DCIV', 'Incendio em imovel', 'urgente'),
  ('DCIV', 'Acidente com produtos perigosos', 'urgente'),
  ('DCIV', 'Vazamento de gas', 'urgente'),
  ('DCIV', 'Vazamento de produtos quimicos', 'urgente'),
  ('DCIV', 'Explosao em imovel', 'urgente'),
  ('DCIV', 'Emergencia em barragens', 'urgente'),
  ('DCIV', 'Mapeamento de areas de risco', 'media'),
  ('DCIV', 'Plano de evacuacao comunitaria', 'media'),
  ('DCIV', 'Abrigos emergenciais', 'alta'),
  ('DCIV', 'Campanhas de prevencao', 'baixa'),
  ('DCIV', 'Outro', 'media'),
  ('GMAM', 'Violencia fisica contra mulher', 'urgente'),
  ('GMAM', 'Violencia psicologica contra mulher', 'alta'),
  ('GMAM', 'Violencia sexual contra mulher', 'urgente'),
  ('GMAM', 'Violencia moral e humilhacao', 'alta'),
  ('GMAM', 'Ameaca e intimidacao', 'urgente'),
  ('GMAM', 'Assedio moral no trabalho', 'alta'),
  ('GMAM', 'Assedio sexual', 'urgente'),
  ('GMAM', 'Agressao com lesao corporal', 'urgente'),
  ('GMAM', 'Tentativa de feminicidio', 'urgente'),
  ('GMAM', 'Maus-tratos a filhas e filhos', 'urgente'),
  ('GMAM', 'Abandono de lar', 'alta'),
  ('GMAM', 'Pensao alimenticia nao paga', 'media'),
  ('GMAM', 'Solicitacao de medida protetiva', 'urgente'),
  ('GMAM', 'Acolhimento emergencial', 'urgente'),
  ('GMAM', 'Acompanhamento psicologico', 'media'),
  ('GMAM', 'Acompanhamento social', 'media'),
  ('GMAM', 'Assessoria juridica gratuita', 'media'),
  ('GMAM', 'Encaminhamento para delegacia da mulher', 'alta'),
  ('GMAM', 'Encaminhamento para casa abrigo', 'urgente'),
  ('GMAM', 'Campanhas de conscientizacao', 'baixa'),
  ('GMAM', 'Palestras sobre direitos da mulher', 'baixa'),
  ('GMAM', 'Grupo de apoio a mulheres', 'baixa'),
  ('GMAM', 'Oficinas de geracao de renda', 'baixa'),
  ('GMAM', 'Denuncia de agressor', 'urgente'),
  ('GMAM', 'Outro', 'media'),
  ('GSU', 'Acidente grave com vitimas', 'urgente'),
  ('GSU', 'Capotamento de veiculo', 'urgente'),
  ('GSU', 'Atropelamento em via', 'urgente'),
  ('GSU', 'Resgate de pessoas em local de dificil acesso', 'urgente'),
  ('GSU', 'Desabamento de imovel com vitimas', 'urgente'),
  ('GSU', 'Incendio em imovel', 'urgente'),
  ('GSU', 'Incendio em veiculo', 'urgente'),
  ('GSU', 'Incendio em area de mata', 'urgente'),
  ('GSU', 'Afogamento em rio ou lago', 'urgente'),
  ('GSU', 'Resgate em altura', 'urgente'),
  ('GSU', 'Resgate em enchente', 'urgente'),
  ('GSU', 'Emergencia medica em via publica', 'urgente'),
  ('GSU', 'Apoio ao SAMU em ocorrencias', 'alta'),
  ('GSU', 'Apoio ao Corpo de Bombeiros', 'alta'),
  ('GSU', 'Apoio a Policia em grandes eventos', 'media'),
  ('GSU', 'Apoio em operacoes de grande porte', 'media'),
  ('GSU', 'Resgate a animais em risco', 'media'),
  ('GSU', 'Emergencia em rodovias', 'urgente'),
  ('GSU', 'Acidente com produtos perigosos', 'urgente'),
  ('GSU', 'Vazamento de produtos toxicos', 'urgente'),
  ('GSU', 'Ambulancia solicitada', 'alta'),
  ('GSU', 'Kit de primeiros socorros', 'baixa'),
  ('GSU', 'Apoio em desastres naturais', 'urgente'),
  ('GSU', 'Simulados de emergencia', 'baixa'),
  ('GSU', 'Outro', 'media')
) AS p(sigla, nome, prioridade)
  WHERE s.sigla = p.sigla
    AND a.secretaria_id = s.id
    AND a.nome = p.nome;
